export const products = [
	{
		img: ['/images/card1.png', '/images/card2.png', '/images/card3.png'],
		category: 'ГОРОДСКОЙ',
		discount: '18%',
		originalPrice: '53 000',
		currentPrice: '43 610',
		gender: 'Женский, Мужской',
		name: 'DISCO',
		linkName: 'disco',
		description:
			' AIST Disco гармонично сочетает в себе легкость движения велосипедов дорожного типа с отличной управляемостью сити–байков, которая обеспечена 24–скоростной трансмиссией с четким механизмом работы от Shimano. Современный дизайн, воплощенный в классических очертаниях и матовом сером окрасе, поистине впечатляет.',
		wheelsSize: '28',
		color: 'графитовый',
		weight: '12,3',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '520 / 540 / 580',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '24',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Дисковые гидравлические Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C'
	},
	{
		img: ['/images/card2.png', '/images/card1.png', '/images/card3.png'],
		category: 'ГОРНЫЙ',
		discount: '18%',
		originalPrice: '36 400',
		currentPrice: '28 000',
		gender: 'Мужской',
		name: 'QUEST DISC 29',
		linkName: 'quest_disc_29',
		description:
			' AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.',
		wheelsSize: '25',
		color: 'черный',
		weight: '9',
		frameMaterial: 'Сталь',
		fork: 'Жесткая, сталь',
		size: '420 / 440 / 480',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '18',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Дисковые гидравлические Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C'
	},
	{
		img: ['/images/card3.png', '/images/card1.png', '/images/card2.png'],
		category: 'ГОРНЫЙ',
		discount: '18%',
		originalPrice: '40 440',
		currentPrice: '33 026',
		gender: 'Мужской',
		name: 'ROCKY 2.0 DISC 29',
		linkName: 'rocky_2.0_disc_29',
		description:
			' HHAHHAHHAHAHAHAHAHHAHAHHAHHHHAHAHHAAHHAAHHAHAHAHAHHAHAHAHAHAHAHAHAHHAHAHAHAHAHAHHAHAHAHAHHAHAHAHAHHAHAHAHAHAHHAHAHAHAHAHAHHAHAHAHAHAHAHHHAHHHHHHHHAHHAHHAHHAHAHHAHAHHHAHAHHAHAHAHHAHHAHAHHAHA.',
		wheelsSize: '28',
		color: 'синий',
		weight: '18',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '620 / 640 / 680',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '30',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Дисковые гидравлические Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C'
	},
	{
		img: ['/images/card1.png', '/images/card2.png', '/images/card3.png'],
		category: 'ГОРОДСКОЙ',
		discount: '18%',
		originalPrice: '53 000',
		currentPrice: '43 610',
		gender: 'Женский, Мужской',
		name: 'DISCO',
		linkName: 'disco2',
		description:
			' AIST Disco гармонично сочетает в себе легкость движения велосипедов дорожного типа с отличной управляемостью сити–байков, которая обеспечена 24–скоростной трансмиссией с четким механизмом работы от Shimano. Современный дизайн, воплощенный в классических очертаниях и матовом сером окрасе, поистине впечатляет.',
		wheelsSize: '28',
		color: 'РоЗоВый',
		weight: '12,3',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '520 / 540 / 580',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '24',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Дисковые гидравлические Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C'
	},
	{
		img: ['/images/card2.png', '/images/card1.png', '/images/card3.png'],
		category: 'ГОРНЫЙ',
		discount: '18%',
		originalPrice: '36 400',
		currentPrice: '28 000',
		gender: 'Мужской',
		name: 'QUEST DISC 29',
		linkName: 'quest_disc_29_2',
		description:
			' AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.',
		wheelsSize: '25',
		color: 'фиолетовыЙ',
		weight: '9',
		frameMaterial: 'Сталь',
		fork: 'Жесткая, сталь',
		size: '420 / 440 / 480',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '18',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Дисковые гидравлические Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C'
	},
	{
		img: ['/images/card3.png', '/images/card1.png', '/images/card2.png'],
		category: 'ГОРНЫЙ',
		discount: '18%',
		originalPrice: '40 440',
		currentPrice: '33 026',
		gender: 'Мужской',
		name: 'ROCKY 2.0 DISC 29',
		linkName: 'rocky_2.0_disc_29_2',
		description:
			' HHAHHAHHAHAHAHAHAHHAHAHHAHHHHAHAHHAAHHAAHHAHAHAHAHHAHAHAHAHAHAHAHAHHAHAHAHAHAHAHHAHAHAHAHHAHAHAHAHHAHAHAHAHAHHAHAHAHAHAHAHHAHAHAHAHAHAHHHAHHHHHHHHAHHAHHAHHAHAHHAHAHHHAHAHHAHAHAHHAHHAHAHHAHA.',
		wheelsSize: '28',
		color: 'голУбой',
		weight: '18',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '620 / 640 / 680',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '30',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Дисковые гидравлические Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C'
	},
	{
		img: ['/images/card1.png', '/images/card2.png', '/images/card3.png'],
		category: 'ГОРОДСКОЙ',
		discount: '18%',
		originalPrice: '53 000',
		currentPrice: '43 610',
		gender: 'Женский, Мужской',
		name: 'DISCO',
		linkName: 'disco3',
		description:
			' AIST Disco гармонично сочетает в себе легкость движения велосипедов дорожного типа с отличной управляемостью сити–байков, которая обеспечена 24–скоростной трансмиссией с четким механизмом работы от Shimano. Современный дизайн, воплощенный в классических очертаниях и матовом сером окрасе, поистине впечатляет.',
		wheelsSize: '28',
		color: 'ораНжеВый',
		weight: '12,3',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '520 / 540 / 580',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '24',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Дисковые гидравлические Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C'
	},
	{
		img: ['/images/card2.png', '/images/card1.png', '/images/card3.png'],
		category: 'ГОРНЫЙ',
		discount: '18%',
		originalPrice: '36 400',
		currentPrice: '28 000',
		gender: 'Мужской',
		name: 'QUEST DISC 29',
		linkName: 'quest_disc_29_3',
		description:
			' AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.',
		wheelsSize: '25',
		color: 'жеЛтый',
		weight: '9',
		frameMaterial: 'Сталь',
		fork: 'Жесткая, сталь',
		size: '420 / 440 / 480',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '18',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Дисковые гидравлические Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C'
	},
	{
		img: ['/images/card3.png', '/images/card1.png', '/images/card2.png'],
		category: 'ГОРНЫЙ',
		discount: '18%',
		originalPrice: '40 440',
		currentPrice: '33 026',
		gender: 'Мужской',
		name: 'ROCKY 2.0 DISC 29',
		linkName: 'rocky_2.0_disc_29_3',
		description:
			' HHAHHAHHAHAHAHAHAHHAHAHHAHHHHAHAHHAAHHAAHHAHAHAHAHHAHAHAHAHAHAHAHAHHAHAHAHAHAHAHHAHAHAHAHHAHAHAHAHHAHAHAHAHAHHAHAHAHAHAHAHHAHAHAHAHAHAHHHAHHHHHHHHAHHAHHAHHAHAHHAHAHHHAHAHHAHAHAHHAHHAHAHHAHA.',
		wheelsSize: '28',
		color: 'зелЕный',
		weight: '18',
		frameMaterial: 'Алюминий',
		fork: 'Жесткая, алюминий',
		size: '620 / 640 / 680',
		manettes: 'Shimano SL–M310',
		frontDerailleur: 'Shimano FD–TY710',
		rearDerailleur: 'Shimano RD–M360',
		system: 'Shimano FC–TX801 48 x 38 x 28T, 170 мм ',
		cassetteAndRatchet: 'Shimano HG200–8, 12–32T',
		speed: '30',
		carriage: 'Feimin FP–B902, картридж ',
		brakes: 'Дисковые гидравлические Shimano MT200 / M315 160 мм',
		bushings: 'Shimano HB–TX505, 32H',
		rubber: 'Kenda 700 x 38C'
	}
]

export const slides = [
	{
		image: '/images/vel_1.png',
		info: {
			title: 'AIST Rocky',
			subtitle: '1.0 Disc 29',
			details: [
				{ label: 'Амортизация', value: 'Хардтейл' },
				{ label: 'Размер рамы', value: '17,5" / 19,5"' },
				{ label: 'Материал рамы', value: 'Алюминий' },
				{ label: 'Тип рамы', value: 'Закрытая' }
			]
		}
	},
	{
		image: '/images/vel_2.png',
		info: {
			title: 'Minsk',
			subtitle: 'CX 650',
			details: [
				{
					label: 'Амортизация',
					value: 'Пружинно-гидравлическая'
				},
				{ label: 'Высота по седлу', value: '850 мм' },
				{ label: 'Материал рамы', value: 'Сталь' },
				{ label: 'Тип рамы', value: 'Закрытая' }
			]
		}
	},
	{
		image: '/images/vel_3.png',
		info: {
			title: 'AIST Rocky',
			subtitle: '3.0 Disc 29',
			details: [
				{ label: 'Амортизация', value: 'Полный' },
				{ label: 'Размер рамы', value: '19,5" / 21,5"' },
				{ label: 'Материал рамы', value: 'Карбон' },
				{ label: 'Тип рамы', value: 'Закрытая' }
			]
		}
	}
]

export const aboutUsText = {}
